/* Commandes de purge de la base de données */

DROP TABLE LIBELLE_GENRE CASCADE CONSTRAINTS;
DROP TABLE OUVRAGE CASCADE CONSTRAINTS;
DROP TABLE EXEMPLAIRE CASCADE CONSTRAINTS;
DROP TABLE MEMBRE CASCADE CONSTRAINTS;
DROP TABLE EMPRUNTS CASCADE CONSTRAINTS;
DROP SEQUENCE IDmember_seq;
DROP SYNONYM ABONNES;
DROP TABLE DETAILS CASCADE CONSTRAINTS;
DROP VIEW Nb_Emprunts_Ouvrage;
DROP VIEW Nb_Ouvrage_Membre;
DROP TABLE TEMP_LOCATION_TITRE;
DROP TABLE TEMP_LOCATION_EXEMPLAIRE;

